apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: massmach/my-app:a0899e3b705eff0f09f2a5b960afafc8a3b7d604
        ports:
        - containerPort: 5000
