name: GitOps workflow with ArgoCD
on: 
    push:
        branches:
            - main 

jobs: 
    build: 
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
              with: 
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                fetch-depth: 0
            - name: Build Docker Image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}